# Generated by Django 6.0.3 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_alter_movie_country_alter_movie_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('can_change_movies', 'Can change movies')]},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_moderate_reviews', 'Can moderate reviews')]},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
    ]
